version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend_testing/docuchat-ai (1)
    ports:
      - "3000:3000"
    volumes:
      - ./frontend_testing/docuchat-ai (1):/app
    environment:
      - NODE_ENV=development
