# base image
FROM node:18

# working directory
WORKDIR /app

# install dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# copy rest of the code
COPY . .

# expose the port Next.js runs on
EXPOSE 3000

# start dev server
CMD ["npm", "run", "dev"]
